# Generated by Django 3.1.4 on 2020-12-19 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dersadı', models.CharField(max_length=15)),
                ('konu', models.CharField(max_length=50)),
                ('altkonu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sınavlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinavtipi', models.CharField(max_length=25)),
                ('sinavzamanata', models.DateTimeField()),
                ('sinavdogrusayisi', models.PositiveSmallIntegerField()),
                ('sinavyanlissayisi', models.PositiveSmallIntegerField()),
                ('sınavbossayisi', models.PositiveSmallIntegerField()),
                ('altkonu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDatabase.ders')),
            ],
        ),
        migrations.CreateModel(
            name='DersCalısGoruntule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozetekle', models.TextField()),
                ('zamanata', models.DateTimeField()),
                ('islenmedurumu', models.BooleanField(default='false')),
                ('altkonu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDatabase.ders')),
            ],
        ),
        migrations.CreateModel(
            name='CanlıDersKaydı',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=15)),
                ('platformzamanata', models.DateTimeField()),
                ('altkonu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDatabase.ders')),
            ],
        ),
    ]
