# Generated by Django 3.1.4 on 2020-12-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canlıderskaydı',
            old_name='altkonu',
            new_name='canliderskonu',
        ),
        migrations.RenameField(
            model_name='derscalısgoruntule',
            old_name='altkonu',
            new_name='konucalısgoruntule',
        ),
        migrations.RenameField(
            model_name='sınavlar',
            old_name='altkonu',
            new_name='sınavaltkonu',
        ),
    ]
